package com.mk.hms.model;

import java.util.Date;

public class AopLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_aop_log.id
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_aop_log.userid
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_aop_log.username
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_aop_log.loginname
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_aop_log.url
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_aop_log.time
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_aop_log.errormsg
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    private String errormsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_aop_log.ip
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_aop_log.sys
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    private String sys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_aop_log.hotelid
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    private Long hotelid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_aop_log.id
     *
     * @return the value of h_aop_log.id
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_aop_log.id
     *
     * @param id the value for h_aop_log.id
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_aop_log.userid
     *
     * @return the value of h_aop_log.userid
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_aop_log.userid
     *
     * @param userid the value for h_aop_log.userid
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_aop_log.username
     *
     * @return the value of h_aop_log.username
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_aop_log.username
     *
     * @param username the value for h_aop_log.username
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_aop_log.loginname
     *
     * @return the value of h_aop_log.loginname
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_aop_log.loginname
     *
     * @param loginname the value for h_aop_log.loginname
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_aop_log.url
     *
     * @return the value of h_aop_log.url
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_aop_log.url
     *
     * @param url the value for h_aop_log.url
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_aop_log.time
     *
     * @return the value of h_aop_log.time
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_aop_log.time
     *
     * @param time the value for h_aop_log.time
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_aop_log.errormsg
     *
     * @return the value of h_aop_log.errormsg
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public String getErrormsg() {
        return errormsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_aop_log.errormsg
     *
     * @param errormsg the value for h_aop_log.errormsg
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public void setErrormsg(String errormsg) {
        this.errormsg = errormsg == null ? null : errormsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_aop_log.ip
     *
     * @return the value of h_aop_log.ip
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_aop_log.ip
     *
     * @param ip the value for h_aop_log.ip
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_aop_log.sys
     *
     * @return the value of h_aop_log.sys
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public String getSys() {
        return sys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_aop_log.sys
     *
     * @param sys the value for h_aop_log.sys
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public void setSys(String sys) {
        this.sys = sys == null ? null : sys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_aop_log.hotelid
     *
     * @return the value of h_aop_log.hotelid
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public Long getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_aop_log.hotelid
     *
     * @param hotelid the value for h_aop_log.hotelid
     *
     * @mbggenerated Thu Aug 27 18:10:29 CST 2015
     */
    public void setHotelid(Long hotelid) {
        this.hotelid = hotelid;
    }
}