package com.mk.hms.model;

public class EHotelBussinesszone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_hotelbussinesszone.id
     *
     * @mbggenerated Sun Aug 02 12:40:23 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_hotelbussinesszone.businessZoneId
     *
     * @mbggenerated Sun Aug 02 12:40:23 CST 2015
     */
    private Long businessZoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_hotelbussinesszone.hotelId
     *
     * @mbggenerated Sun Aug 02 12:40:23 CST 2015
     */
    private Long hotelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_hotelbussinesszone.id
     *
     * @return the value of e_hotelbussinesszone.id
     *
     * @mbggenerated Sun Aug 02 12:40:23 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_hotelbussinesszone.id
     *
     * @param id the value for e_hotelbussinesszone.id
     *
     * @mbggenerated Sun Aug 02 12:40:23 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_hotelbussinesszone.businessZoneId
     *
     * @return the value of e_hotelbussinesszone.businessZoneId
     *
     * @mbggenerated Sun Aug 02 12:40:23 CST 2015
     */
    public Long getBusinessZoneId() {
        return businessZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_hotelbussinesszone.businessZoneId
     *
     * @param businessZoneId the value for e_hotelbussinesszone.businessZoneId
     *
     * @mbggenerated Sun Aug 02 12:40:23 CST 2015
     */
    public void setBusinessZoneId(Long businessZoneId) {
        this.businessZoneId = businessZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_hotelbussinesszone.hotelId
     *
     * @return the value of e_hotelbussinesszone.hotelId
     *
     * @mbggenerated Sun Aug 02 12:40:23 CST 2015
     */
    public Long getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_hotelbussinesszone.hotelId
     *
     * @param hotelId the value for e_hotelbussinesszone.hotelId
     *
     * @mbggenerated Sun Aug 02 12:40:23 CST 2015
     */
    public void setHotelId(Long hotelId) {
        this.hotelId = hotelId;
    }
}