package com.mk.hms.model;

import java.math.BigDecimal;

public class ERoomtypeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_roomtype_info.id
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_roomtype_info.roomtypeid
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    private Long roomTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_roomtype_info.minarea
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    private BigDecimal minArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_roomtype_info.maxarea
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    private BigDecimal maxArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_roomtype_info.bedtype
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    private Long bedType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_roomtype_info.bedsize
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    private String bedSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_roomtype_info.pics
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    private String pics;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_roomtype_info.id
     *
     * @return the value of e_roomtype_info.id
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_roomtype_info.id
     *
     * @param id the value for e_roomtype_info.id
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_roomtype_info.roomtypeid
     *
     * @return the value of e_roomtype_info.roomtypeid
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    public Long getRoomTypeId() {
        return roomTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_roomtype_info.roomtypeid
     *
     * @param roomTypeId the value for e_roomtype_info.roomtypeid
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    public void setRoomTypeId(Long roomTypeId) {
        this.roomTypeId = roomTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_roomtype_info.minarea
     *
     * @return the value of e_roomtype_info.minarea
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    public BigDecimal getMinArea() {
        return minArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_roomtype_info.minarea
     *
     * @param minArea the value for e_roomtype_info.minarea
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    public void setMinArea(BigDecimal minArea) {
        this.minArea = minArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_roomtype_info.maxarea
     *
     * @return the value of e_roomtype_info.maxarea
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    public BigDecimal getMaxArea() {
        return maxArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_roomtype_info.maxarea
     *
     * @param maxArea the value for e_roomtype_info.maxarea
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    public void setMaxArea(BigDecimal maxArea) {
        this.maxArea = maxArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_roomtype_info.bedtype
     *
     * @return the value of e_roomtype_info.bedtype
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    public Long getBedType() {
        return bedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_roomtype_info.bedtype
     *
     * @param bedType the value for e_roomtype_info.bedtype
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    public void setBedType(Long bedType) {
        this.bedType = bedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_roomtype_info.bedsize
     *
     * @return the value of e_roomtype_info.bedsize
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    public String getBedSize() {
        return bedSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_roomtype_info.bedsize
     *
     * @param bedSize the value for e_roomtype_info.bedsize
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    public void setBedSize(String bedSize) {
        this.bedSize = bedSize == null ? null : bedSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_roomtype_info.pics
     *
     * @return the value of e_roomtype_info.pics
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    public String getPics() {
        return pics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_roomtype_info.pics
     *
     * @param pics the value for e_roomtype_info.pics
     *
     * @mbggenerated Wed Jul 29 07:42:12 CST 2015
     */
    public void setPics(String pics) {
        this.pics = pics == null ? null : pics.trim();
    }
}