package com.mk.hms.model;

import java.math.BigDecimal;
import java.util.Date;

public class ExtBillOrders {
	private long dfbtje;
	private long yfbtje;
	private int OrderStatus;
	private Date orderCreateTime;
	
	
	
	public Date getOrderCreateTime() {
		return orderCreateTime;
	}

	public void setOrderCreateTime(Date orderCreateTime) {
		this.orderCreateTime = orderCreateTime;
	}

	public int getOrderStatus() {
		return OrderStatus;
	}

	public void setOrderStatus(int orderStatus) {
		OrderStatus = orderStatus;
	}

	public int getInvalidreanson() {
		return invalidreanson;
	}

	public void setInvalidreanson(int invalidreanson) {
		this.invalidreanson = invalidreanson;
	}

	private int invalidreanson;
	
	
    public long getDfbtje() {
		return dfbtje;
	}

	public void setDfbtje(long dfbtje) {
		this.dfbtje = dfbtje;
	}

	public long getYfbtje() {
		return yfbtje;
	}

	public void setYfbtje(long yfbtje) {
		this.yfbtje = yfbtje;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.id
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.hotelId
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private Long hotelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.orderId
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.orderType
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private Long orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.roomTypeName
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private String roomTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.roomNo
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private String roomNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.beginTime
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.endTime
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.dayNumber
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private Integer dayNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.allCost
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private BigDecimal allCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.userCost
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private BigDecimal userCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.cutCost
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private BigDecimal cutCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.hotelGive
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private BigDecimal hotelGive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.otherGive
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private BigDecimal otherGive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.serviceCost
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private BigDecimal serviceCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.createTime
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.pId
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.isPromotion
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private Integer ispromotion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.Invalidreason
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private Integer Invalidreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.payStatus
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private Integer paystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_orders.spreadUser
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    private Long spreaduser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.id
     *
     * @return the value of b_bill_orders.id
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.id
     *
     * @param id the value for b_bill_orders.id
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.hotelId
     *
     * @return the value of b_bill_orders.hotelId
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public Long getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.hotelId
     *
     * @param hotelId the value for b_bill_orders.hotelId
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setHotelId(Long hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.orderId
     *
     * @return the value of b_bill_orders.orderId
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.orderId
     *
     * @param orderId the value for b_bill_orders.orderId
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.orderType
     *
     * @return the value of b_bill_orders.orderType
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public Long getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.orderType
     *
     * @param orderType the value for b_bill_orders.orderType
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setOrderType(Long orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.roomTypeName
     *
     * @return the value of b_bill_orders.roomTypeName
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public String getRoomTypeName() {
        return roomTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.roomTypeName
     *
     * @param roomTypeName the value for b_bill_orders.roomTypeName
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setRoomTypeName(String roomTypeName) {
        this.roomTypeName = roomTypeName == null ? null : roomTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.roomNo
     *
     * @return the value of b_bill_orders.roomNo
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public String getRoomNo() {
        return roomNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.roomNo
     *
     * @param roomNo the value for b_bill_orders.roomNo
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo == null ? null : roomNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.beginTime
     *
     * @return the value of b_bill_orders.beginTime
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.beginTime
     *
     * @param beginTime the value for b_bill_orders.beginTime
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.endTime
     *
     * @return the value of b_bill_orders.endTime
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.endTime
     *
     * @param endTime the value for b_bill_orders.endTime
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.dayNumber
     *
     * @return the value of b_bill_orders.dayNumber
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public Integer getDayNumber() {
        return dayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.dayNumber
     *
     * @param dayNumber the value for b_bill_orders.dayNumber
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setDayNumber(Integer dayNumber) {
        this.dayNumber = dayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.allCost
     *
     * @return the value of b_bill_orders.allCost
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public BigDecimal getAllCost() {
        return allCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.allCost
     *
     * @param allCost the value for b_bill_orders.allCost
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setAllCost(BigDecimal allCost) {
        this.allCost = allCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.userCost
     *
     * @return the value of b_bill_orders.userCost
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public BigDecimal getUserCost() {
        return userCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.userCost
     *
     * @param userCost the value for b_bill_orders.userCost
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setUserCost(BigDecimal userCost) {
        this.userCost = userCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.cutCost
     *
     * @return the value of b_bill_orders.cutCost
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public BigDecimal getCutCost() {
        return cutCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.cutCost
     *
     * @param cutCost the value for b_bill_orders.cutCost
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setCutCost(BigDecimal cutCost) {
        this.cutCost = cutCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.hotelGive
     *
     * @return the value of b_bill_orders.hotelGive
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public BigDecimal getHotelGive() {
        return hotelGive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.hotelGive
     *
     * @param hotelGive the value for b_bill_orders.hotelGive
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setHotelGive(BigDecimal hotelGive) {
        this.hotelGive = hotelGive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.otherGive
     *
     * @return the value of b_bill_orders.otherGive
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public BigDecimal getOtherGive() {
        return otherGive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.otherGive
     *
     * @param otherGive the value for b_bill_orders.otherGive
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setOtherGive(BigDecimal otherGive) {
        this.otherGive = otherGive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.serviceCost
     *
     * @return the value of b_bill_orders.serviceCost
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public BigDecimal getServiceCost() {
        return serviceCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.serviceCost
     *
     * @param serviceCost the value for b_bill_orders.serviceCost
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setServiceCost(BigDecimal serviceCost) {
        this.serviceCost = serviceCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.createTime
     *
     * @return the value of b_bill_orders.createTime
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.createTime
     *
     * @param createTime the value for b_bill_orders.createTime
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.pId
     *
     * @return the value of b_bill_orders.pId
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.pId
     *
     * @param pid the value for b_bill_orders.pId
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.isPromotion
     *
     * @return the value of b_bill_orders.isPromotion
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public Integer getIspromotion() {
        return ispromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.isPromotion
     *
     * @param ispromotion the value for b_bill_orders.isPromotion
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setIspromotion(Integer ispromotion) {
        this.ispromotion = ispromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.Invalidreason
     *
     * @return the value of b_bill_orders.Invalidreason
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public Integer getInvalidreason() {
        return Invalidreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.Invalidreason
     *
     * @param Invalidreason the value for b_bill_orders.Invalidreason
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setInvalidreason(Integer Invalidreason) {
        this.Invalidreason = Invalidreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.payStatus
     *
     * @return the value of b_bill_orders.payStatus
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public Integer getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.payStatus
     *
     * @param paystatus the value for b_bill_orders.payStatus
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setPaystatus(Integer paystatus) {
        this.paystatus = paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_orders.spreadUser
     *
     * @return the value of b_bill_orders.spreadUser
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public Long getSpreaduser() {
        return spreaduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_orders.spreadUser
     *
     * @param spreaduser the value for b_bill_orders.spreadUser
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    public void setSpreaduser(Long spreaduser) {
        this.spreaduser = spreaduser;
    }
}