package com.mk.hms.model;

import java.math.BigDecimal;
import java.util.Date;

public class ExtBillConfirmCheck {
	private long yfbtje;
	private BigDecimal availablemoney;
	private long dfbtje;
	private int OrderStatus;
	private int Invalidreason;
	
	private int preNum;
	private int toNum;	
	private String isFreeze;
	private  BigDecimal objectionChangeCost;
	private int financeStatus;
	private String isThreshold;
	private  BigDecimal readjustcost;
	
	
    public BigDecimal getReadjustcost() {
		return readjustcost;
	}

	public void setReadjustcost(BigDecimal readjustcost) {
		this.readjustcost = readjustcost;
	}

	public String getIsThreshold() {
		return isThreshold;
	}

	public void setIsThreshold(String isThreshold) {
		this.isThreshold = isThreshold;
	}

	public BigDecimal getAvailablemoney() {
		return availablemoney;
	}

	public void setAvailablemoney(BigDecimal availablemoney) {
		this.availablemoney = availablemoney;
	}

	public int getFinanceStatus() {
		return financeStatus;
	}

	public void setFinanceStatus(int financeStatus) {
		this.financeStatus = financeStatus;
	}

	public BigDecimal getObjectionChangeCost() {
		return objectionChangeCost;
	}

	public void setObjectionChangeCost(BigDecimal objectionChangeCost) {
		this.objectionChangeCost = objectionChangeCost;
	}

	public String getIsFreeze() {
		return isFreeze;
	}

	public void setIsFreeze(String isFreeze) {
		this.isFreeze = isFreeze;
	}

	public int getOrderStatus() {
		return OrderStatus;
	}

	public void setOrderStatus(int orderStatus) {
		OrderStatus = orderStatus;
	}

	

	public int getInvalidreason() {
		return Invalidreason;
	}

	public void setInvalidreason(int invalidreason) {
		Invalidreason = invalidreason;
	}

	public long getYfbtje() {
		return yfbtje;
	}

	public void setYfbtje(long yfbtje) {
		this.yfbtje = yfbtje;
	}

	public long getDfbtje() {
		return dfbtje;
	}

	public void setDfbtje(long dfbtje) {
		this.dfbtje = dfbtje;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.id
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.hotelid
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private Long hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.confirmstatus
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private Integer confirmstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.checkstatus
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private Integer checkstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.checkuserid
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private Long checkuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.checkusername
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private String checkusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.checktime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private Date checktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.confirmtime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private Date confirmtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.billtime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private String billtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.begintime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private Date begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.endtime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.ordernum
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private Integer ordernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.topaynum
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private Integer topaynum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.topaymon
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private BigDecimal topaymon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.hoteldiscountcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private BigDecimal hoteldiscountcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.servicecost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private BigDecimal servicecost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.otherdiscountcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private BigDecimal otherdiscountcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.cutofforders
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private Integer cutofforders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.cutoffcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private BigDecimal cutoffcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.prepaymentnum
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private Integer prepaymentnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.prepaymentcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private BigDecimal prepaymentcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.changecost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private BigDecimal changecost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.billcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private BigDecimal billcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.finalcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private BigDecimal finalcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.confirmuserid
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private Long confirmuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.confirmusername
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private String confirmusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.createTime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.hotelcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private BigDecimal hotelcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.splitcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private BigDecimal splitcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bill_confirm_check.invaildcutofforders
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    private Integer invaildcutofforders;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.id
     *
     * @return the value of b_bill_confirm_check.id
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.id
     *
     * @param id the value for b_bill_confirm_check.id
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.hotelid
     *
     * @return the value of b_bill_confirm_check.hotelid
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public Long getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.hotelid
     *
     * @param hotelid the value for b_bill_confirm_check.hotelid
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setHotelid(Long hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.confirmstatus
     *
     * @return the value of b_bill_confirm_check.confirmstatus
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public Integer getConfirmstatus() {
        return confirmstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.confirmstatus
     *
     * @param confirmstatus the value for b_bill_confirm_check.confirmstatus
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setConfirmstatus(Integer confirmstatus) {
        this.confirmstatus = confirmstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.checkstatus
     *
     * @return the value of b_bill_confirm_check.checkstatus
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public Integer getCheckstatus() {
        return checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.checkstatus
     *
     * @param checkstatus the value for b_bill_confirm_check.checkstatus
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setCheckstatus(Integer checkstatus) {
        this.checkstatus = checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.checkuserid
     *
     * @return the value of b_bill_confirm_check.checkuserid
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public Long getCheckuserid() {
        return checkuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.checkuserid
     *
     * @param checkuserid the value for b_bill_confirm_check.checkuserid
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setCheckuserid(Long checkuserid) {
        this.checkuserid = checkuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.checkusername
     *
     * @return the value of b_bill_confirm_check.checkusername
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public String getCheckusername() {
        return checkusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.checkusername
     *
     * @param checkusername the value for b_bill_confirm_check.checkusername
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setCheckusername(String checkusername) {
        this.checkusername = checkusername == null ? null : checkusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.checktime
     *
     * @return the value of b_bill_confirm_check.checktime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.checktime
     *
     * @param checktime the value for b_bill_confirm_check.checktime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.confirmtime
     *
     * @return the value of b_bill_confirm_check.confirmtime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public Date getConfirmtime() {
        return confirmtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.confirmtime
     *
     * @param confirmtime the value for b_bill_confirm_check.confirmtime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setConfirmtime(Date confirmtime) {
        this.confirmtime = confirmtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.billtime
     *
     * @return the value of b_bill_confirm_check.billtime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public String getBilltime() {
        return billtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.billtime
     *
     * @param billtime the value for b_bill_confirm_check.billtime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setBilltime(String billtime) {
        this.billtime = billtime == null ? null : billtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.begintime
     *
     * @return the value of b_bill_confirm_check.begintime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.begintime
     *
     * @param begintime the value for b_bill_confirm_check.begintime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.endtime
     *
     * @return the value of b_bill_confirm_check.endtime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.endtime
     *
     * @param endtime the value for b_bill_confirm_check.endtime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.ordernum
     *
     * @return the value of b_bill_confirm_check.ordernum
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.ordernum
     *
     * @param ordernum the value for b_bill_confirm_check.ordernum
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.topaynum
     *
     * @return the value of b_bill_confirm_check.topaynum
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public Integer getTopaynum() {
        return topaynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.topaynum
     *
     * @param topaynum the value for b_bill_confirm_check.topaynum
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setTopaynum(Integer topaynum) {
        this.topaynum = topaynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.topaymon
     *
     * @return the value of b_bill_confirm_check.topaymon
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public BigDecimal getTopaymon() {
        return topaymon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.topaymon
     *
     * @param topaymon the value for b_bill_confirm_check.topaymon
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setTopaymon(BigDecimal topaymon) {
        this.topaymon = topaymon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.hoteldiscountcost
     *
     * @return the value of b_bill_confirm_check.hoteldiscountcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public BigDecimal getHoteldiscountcost() {
        return hoteldiscountcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.hoteldiscountcost
     *
     * @param hoteldiscountcost the value for b_bill_confirm_check.hoteldiscountcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setHoteldiscountcost(BigDecimal hoteldiscountcost) {
        this.hoteldiscountcost = hoteldiscountcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.servicecost
     *
     * @return the value of b_bill_confirm_check.servicecost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public BigDecimal getServicecost() {
        return servicecost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.servicecost
     *
     * @param servicecost the value for b_bill_confirm_check.servicecost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setServicecost(BigDecimal servicecost) {
        this.servicecost = servicecost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.otherdiscountcost
     *
     * @return the value of b_bill_confirm_check.otherdiscountcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public BigDecimal getOtherdiscountcost() {
        return otherdiscountcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.otherdiscountcost
     *
     * @param otherdiscountcost the value for b_bill_confirm_check.otherdiscountcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setOtherdiscountcost(BigDecimal otherdiscountcost) {
        this.otherdiscountcost = otherdiscountcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.cutofforders
     *
     * @return the value of b_bill_confirm_check.cutofforders
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public Integer getCutofforders() {
        return cutofforders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.cutofforders
     *
     * @param cutofforders the value for b_bill_confirm_check.cutofforders
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setCutofforders(Integer cutofforders) {
        this.cutofforders = cutofforders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.cutoffcost
     *
     * @return the value of b_bill_confirm_check.cutoffcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public BigDecimal getCutoffcost() {
        return cutoffcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.cutoffcost
     *
     * @param cutoffcost the value for b_bill_confirm_check.cutoffcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setCutoffcost(BigDecimal cutoffcost) {
        this.cutoffcost = cutoffcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.prepaymentnum
     *
     * @return the value of b_bill_confirm_check.prepaymentnum
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public Integer getPrepaymentnum() {
        return prepaymentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.prepaymentnum
     *
     * @param prepaymentnum the value for b_bill_confirm_check.prepaymentnum
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setPrepaymentnum(Integer prepaymentnum) {
        this.prepaymentnum = prepaymentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.prepaymentcost
     *
     * @return the value of b_bill_confirm_check.prepaymentcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public BigDecimal getPrepaymentcost() {
        return prepaymentcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.prepaymentcost
     *
     * @param prepaymentcost the value for b_bill_confirm_check.prepaymentcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setPrepaymentcost(BigDecimal prepaymentcost) {
        this.prepaymentcost = prepaymentcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.changecost
     *
     * @return the value of b_bill_confirm_check.changecost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public BigDecimal getChangecost() {
        return changecost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.changecost
     *
     * @param changecost the value for b_bill_confirm_check.changecost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setChangecost(BigDecimal changecost) {
        this.changecost = changecost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.billcost
     *
     * @return the value of b_bill_confirm_check.billcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public BigDecimal getBillcost() {
        return billcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.billcost
     *
     * @param billcost the value for b_bill_confirm_check.billcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setBillcost(BigDecimal billcost) {
        this.billcost = billcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.finalcost
     *
     * @return the value of b_bill_confirm_check.finalcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public BigDecimal getFinalcost() {
        return finalcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.finalcost
     *
     * @param finalcost the value for b_bill_confirm_check.finalcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setFinalcost(BigDecimal finalcost) {
        this.finalcost = finalcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.confirmuserid
     *
     * @return the value of b_bill_confirm_check.confirmuserid
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public Long getConfirmuserid() {
        return confirmuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.confirmuserid
     *
     * @param confirmuserid the value for b_bill_confirm_check.confirmuserid
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setConfirmuserid(Long confirmuserid) {
        this.confirmuserid = confirmuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.confirmusername
     *
     * @return the value of b_bill_confirm_check.confirmusername
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public String getConfirmusername() {
        return confirmusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.confirmusername
     *
     * @param confirmusername the value for b_bill_confirm_check.confirmusername
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setConfirmusername(String confirmusername) {
        this.confirmusername = confirmusername == null ? null : confirmusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.createTime
     *
     * @return the value of b_bill_confirm_check.createTime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.createTime
     *
     * @param createtime the value for b_bill_confirm_check.createTime
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.hotelcost
     *
     * @return the value of b_bill_confirm_check.hotelcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public BigDecimal getHotelcost() {
        return hotelcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.hotelcost
     *
     * @param hotelcost the value for b_bill_confirm_check.hotelcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setHotelcost(BigDecimal hotelcost) {
        this.hotelcost = hotelcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.splitcost
     *
     * @return the value of b_bill_confirm_check.splitcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public BigDecimal getSplitcost() {
        return splitcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.splitcost
     *
     * @param splitcost the value for b_bill_confirm_check.splitcost
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setSplitcost(BigDecimal splitcost) {
        this.splitcost = splitcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bill_confirm_check.invaildcutofforders
     *
     * @return the value of b_bill_confirm_check.invaildcutofforders
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public Integer getInvaildcutofforders() {
        return invaildcutofforders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bill_confirm_check.invaildcutofforders
     *
     * @param invaildcutofforders the value for b_bill_confirm_check.invaildcutofforders
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    public void setInvaildcutofforders(Integer invaildcutofforders) {
        this.invaildcutofforders = invaildcutofforders;
    }

	public int getPreNum() {
		return preNum;
	}

	public void setPreNum(int preNum) {
		this.preNum = preNum;
	}

	public int getToNum() {
		return toNum;
	}

	public void setToNum(int toNum) {
		this.toNum = toNum;
	}
}