package com.mk.hms.model;

import java.util.Date;

public class HotelOperateLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_operate_log.id
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_operate_log.hotelid
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    private Long hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_operate_log.hotelname
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    private String hotelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_operate_log.usercode
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    private Long usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_operate_log.username
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_operate_log.checktime
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    private Date checktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_operate_log.checktype
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    private Integer checktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_operate_log.checktypename
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    private String checktypename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_operate_log.id
     *
     * @return the value of t_hotel_operate_log.id
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_operate_log.id
     *
     * @param id the value for t_hotel_operate_log.id
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_operate_log.hotelid
     *
     * @return the value of t_hotel_operate_log.hotelid
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    public Long getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_operate_log.hotelid
     *
     * @param hotelid the value for t_hotel_operate_log.hotelid
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    public void setHotelid(Long hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_operate_log.hotelname
     *
     * @return the value of t_hotel_operate_log.hotelname
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    public String getHotelname() {
        return hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_operate_log.hotelname
     *
     * @param hotelname the value for t_hotel_operate_log.hotelname
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    public void setHotelname(String hotelname) {
        this.hotelname = hotelname == null ? null : hotelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_operate_log.usercode
     *
     * @return the value of t_hotel_operate_log.usercode
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    public Long getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_operate_log.usercode
     *
     * @param usercode the value for t_hotel_operate_log.usercode
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    public void setUsercode(Long usercode) {
        this.usercode = usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_operate_log.username
     *
     * @return the value of t_hotel_operate_log.username
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_operate_log.username
     *
     * @param username the value for t_hotel_operate_log.username
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_operate_log.checktime
     *
     * @return the value of t_hotel_operate_log.checktime
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_operate_log.checktime
     *
     * @param checktime the value for t_hotel_operate_log.checktime
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_operate_log.checktype
     *
     * @return the value of t_hotel_operate_log.checktype
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    public Integer getChecktype() {
        return checktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_operate_log.checktype
     *
     * @param checktype the value for t_hotel_operate_log.checktype
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    public void setChecktype(Integer checktype) {
        this.checktype = checktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_operate_log.checktypename
     *
     * @return the value of t_hotel_operate_log.checktypename
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    public String getChecktypename() {
        return checktypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_operate_log.checktypename
     *
     * @param checktypename the value for t_hotel_operate_log.checktypename
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    public void setChecktypename(String checktypename) {
        this.checktypename = checktypename == null ? null : checktypename.trim();
    }
}