package com.mk.hms.model;

import java.math.BigDecimal;
import java.util.Date;

public class HotelScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.id
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.roomid
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private Long roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.roomtypeid
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private Long roomTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.hotelid
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private Long hotelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.score
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private String score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.createtime
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.orderid
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.grade
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private BigDecimal grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.hotelscore
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private String hotelScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.servicescore
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private String serviceScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.isreply
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private Integer isreply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.isaduit
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private Integer isaduit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.hotelscoretime
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private Date hotelscoretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.servicescoretime
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private Date servicescoretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.isvisible
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private String isvisible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.status
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.type
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.parentID
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private Long parentID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.mid
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private Long mId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_score.pics
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    private String pics;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.id
     *
     * @return the value of t_hotel_score.id
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.id
     *
     * @param id the value for t_hotel_score.id
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.roomid
     *
     * @return the value of t_hotel_score.roomid
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public Long getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.roomid
     *
     * @param roomId the value for t_hotel_score.roomid
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setRoomId(Long roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.roomtypeid
     *
     * @return the value of t_hotel_score.roomtypeid
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public Long getRoomTypeId() {
        return roomTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.roomtypeid
     *
     * @param roomTypeId the value for t_hotel_score.roomtypeid
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setRoomTypeId(Long roomTypeId) {
        this.roomTypeId = roomTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.hotelid
     *
     * @return the value of t_hotel_score.hotelid
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public Long getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.hotelid
     *
     * @param hotelId the value for t_hotel_score.hotelid
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setHotelId(Long hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.score
     *
     * @return the value of t_hotel_score.score
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.score
     *
     * @param score the value for t_hotel_score.score
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.createtime
     *
     * @return the value of t_hotel_score.createtime
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.createtime
     *
     * @param createTime the value for t_hotel_score.createtime
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.orderid
     *
     * @return the value of t_hotel_score.orderid
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.orderid
     *
     * @param orderId the value for t_hotel_score.orderid
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.grade
     *
     * @return the value of t_hotel_score.grade
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public BigDecimal getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.grade
     *
     * @param grade the value for t_hotel_score.grade
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setGrade(BigDecimal grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.hotelscore
     *
     * @return the value of t_hotel_score.hotelscore
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public String getHotelScore() {
        return hotelScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.hotelscore
     *
     * @param hotelScore the value for t_hotel_score.hotelscore
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setHotelScore(String hotelScore) {
        this.hotelScore = hotelScore == null ? null : hotelScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.servicescore
     *
     * @return the value of t_hotel_score.servicescore
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public String getServiceScore() {
        return serviceScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.servicescore
     *
     * @param serviceScore the value for t_hotel_score.servicescore
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setServiceScore(String serviceScore) {
        this.serviceScore = serviceScore == null ? null : serviceScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.isreply
     *
     * @return the value of t_hotel_score.isreply
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public Integer getIsreply() {
        return isreply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.isreply
     *
     * @param isreply the value for t_hotel_score.isreply
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setIsreply(Integer isreply) {
        this.isreply = isreply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.isaduit
     *
     * @return the value of t_hotel_score.isaduit
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public Integer getIsaduit() {
        return isaduit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.isaduit
     *
     * @param isaduit the value for t_hotel_score.isaduit
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setIsaduit(Integer isaduit) {
        this.isaduit = isaduit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.hotelscoretime
     *
     * @return the value of t_hotel_score.hotelscoretime
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public Date getHotelscoretime() {
        return hotelscoretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.hotelscoretime
     *
     * @param hotelscoretime the value for t_hotel_score.hotelscoretime
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setHotelscoretime(Date hotelscoretime) {
        this.hotelscoretime = hotelscoretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.servicescoretime
     *
     * @return the value of t_hotel_score.servicescoretime
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public Date getServicescoretime() {
        return servicescoretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.servicescoretime
     *
     * @param servicescoretime the value for t_hotel_score.servicescoretime
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setServicescoretime(Date servicescoretime) {
        this.servicescoretime = servicescoretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.isvisible
     *
     * @return the value of t_hotel_score.isvisible
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public String getIsvisible() {
        return isvisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.isvisible
     *
     * @param isvisible the value for t_hotel_score.isvisible
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setIsvisible(String isvisible) {
        this.isvisible = isvisible == null ? null : isvisible.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.status
     *
     * @return the value of t_hotel_score.status
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.status
     *
     * @param status the value for t_hotel_score.status
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.type
     *
     * @return the value of t_hotel_score.type
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.type
     *
     * @param type the value for t_hotel_score.type
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.parentID
     *
     * @return the value of t_hotel_score.parentID
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public Long getParentID() {
        return parentID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.parentID
     *
     * @param parentID the value for t_hotel_score.parentID
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setParentID(Long parentID) {
        this.parentID = parentID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.mid
     *
     * @return the value of t_hotel_score.mid
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public Long getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.mid
     *
     * @param mId the value for t_hotel_score.mid
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setmId(Long mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_score.pics
     *
     * @return the value of t_hotel_score.pics
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public String getPics() {
        return pics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_score.pics
     *
     * @param pics the value for t_hotel_score.pics
     *
     * @mbggenerated Thu Jul 30 11:47:25 CST 2015
     */
    public void setPics(String pics) {
        this.pics = pics == null ? null : pics.trim();
    }
}