package com.mk.hms.model;

public class MRoleUserWithBLOBs extends MRoleUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel.introduction
     *
     * @mbggenerated Wed Jul 22 10:43:14 CST 2015
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel.traffic
     *
     * @mbggenerated Wed Jul 22 10:43:14 CST 2015
     */
    private String traffic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel.hotelpic
     *
     * @mbggenerated Wed Jul 22 10:43:14 CST 2015
     */
    private String hotelpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel.peripheral
     *
     * @mbggenerated Wed Jul 22 10:43:14 CST 2015
     */
    private String peripheral;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel.introduction
     *
     * @return the value of t_hotel.introduction
     *
     * @mbggenerated Wed Jul 22 10:43:14 CST 2015
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel.introduction
     *
     * @param introduction the value for t_hotel.introduction
     *
     * @mbggenerated Wed Jul 22 10:43:14 CST 2015
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel.traffic
     *
     * @return the value of t_hotel.traffic
     *
     * @mbggenerated Wed Jul 22 10:43:14 CST 2015
     */
    public String getTraffic() {
        return traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel.traffic
     *
     * @param traffic the value for t_hotel.traffic
     *
     * @mbggenerated Wed Jul 22 10:43:14 CST 2015
     */
    public void setTraffic(String traffic) {
        this.traffic = traffic == null ? null : traffic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel.hotelpic
     *
     * @return the value of t_hotel.hotelpic
     *
     * @mbggenerated Wed Jul 22 10:43:14 CST 2015
     */
    public String getHotelpic() {
        return hotelpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel.hotelpic
     *
     * @param hotelpic the value for t_hotel.hotelpic
     *
     * @mbggenerated Wed Jul 22 10:43:14 CST 2015
     */
    public void setHotelpic(String hotelpic) {
        this.hotelpic = hotelpic == null ? null : hotelpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel.peripheral
     *
     * @return the value of t_hotel.peripheral
     *
     * @mbggenerated Wed Jul 22 10:43:14 CST 2015
     */
    public String getPeripheral() {
        return peripheral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel.peripheral
     *
     * @param peripheral the value for t_hotel.peripheral
     *
     * @mbggenerated Wed Jul 22 10:43:14 CST 2015
     */
    public void setPeripheral(String peripheral) {
        this.peripheral = peripheral == null ? null : peripheral.trim();
    }
}