package com.mk.hms.model;

import java.io.Serializable;
import java.util.Collection;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

public class MUser implements UserDetails, Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.id
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.name
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.loginname
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.psw
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private String psw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.phone
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.email
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.begintime
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private String begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.endtime
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private String endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.regtime
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private String regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.errorlogin
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private Integer errorlogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.nextchangepswtime
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private String nextchangepswtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.nextchangepswreasion
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private String nextchangepswreasion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.status
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.errorlogintime
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private String errorlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.sys
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private String sys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.isIdap
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private String isidap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.synid
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    private String synid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.id
     *
     * @return the value of m_user.id
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.id
     *
     * @param id the value for m_user.id
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.name
     *
     * @return the value of m_user.name
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.name
     *
     * @param name the value for m_user.name
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.loginname
     *
     * @return the value of m_user.loginname
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.loginname
     *
     * @param loginname the value for m_user.loginname
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.psw
     *
     * @return the value of m_user.psw
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public String getPsw() {
        return psw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.psw
     *
     * @param psw the value for m_user.psw
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setPsw(String psw) {
        this.psw = psw == null ? null : psw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.phone
     *
     * @return the value of m_user.phone
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.phone
     *
     * @param phone the value for m_user.phone
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.email
     *
     * @return the value of m_user.email
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.email
     *
     * @param email the value for m_user.email
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.begintime
     *
     * @return the value of m_user.begintime
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public String getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.begintime
     *
     * @param begintime the value for m_user.begintime
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setBegintime(String begintime) {
        this.begintime = begintime == null ? null : begintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.endtime
     *
     * @return the value of m_user.endtime
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.endtime
     *
     * @param endtime the value for m_user.endtime
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime == null ? null : endtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.regtime
     *
     * @return the value of m_user.regtime
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public String getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.regtime
     *
     * @param regtime the value for m_user.regtime
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setRegtime(String regtime) {
        this.regtime = regtime == null ? null : regtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.errorlogin
     *
     * @return the value of m_user.errorlogin
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public Integer getErrorlogin() {
        return errorlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.errorlogin
     *
     * @param errorlogin the value for m_user.errorlogin
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setErrorlogin(Integer errorlogin) {
        this.errorlogin = errorlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.nextchangepswtime
     *
     * @return the value of m_user.nextchangepswtime
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public String getNextchangepswtime() {
        return nextchangepswtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.nextchangepswtime
     *
     * @param nextchangepswtime the value for m_user.nextchangepswtime
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setNextchangepswtime(String nextchangepswtime) {
        this.nextchangepswtime = nextchangepswtime == null ? null : nextchangepswtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.nextchangepswreasion
     *
     * @return the value of m_user.nextchangepswreasion
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public String getNextchangepswreasion() {
        return nextchangepswreasion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.nextchangepswreasion
     *
     * @param nextchangepswreasion the value for m_user.nextchangepswreasion
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setNextchangepswreasion(String nextchangepswreasion) {
        this.nextchangepswreasion = nextchangepswreasion == null ? null : nextchangepswreasion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.status
     *
     * @return the value of m_user.status
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.status
     *
     * @param status the value for m_user.status
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.errorlogintime
     *
     * @return the value of m_user.errorlogintime
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public String getErrorlogintime() {
        return errorlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.errorlogintime
     *
     * @param errorlogintime the value for m_user.errorlogintime
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setErrorlogintime(String errorlogintime) {
        this.errorlogintime = errorlogintime == null ? null : errorlogintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.sys
     *
     * @return the value of m_user.sys
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public String getSys() {
        return sys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.sys
     *
     * @param sys the value for m_user.sys
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setSys(String sys) {
        this.sys = sys == null ? null : sys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.isIdap
     *
     * @return the value of m_user.isIdap
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public String getIsidap() {
        return isidap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.isIdap
     *
     * @param isidap the value for m_user.isIdap
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setIsidap(String isidap) {
        this.isidap = isidap == null ? null : isidap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.synid
     *
     * @return the value of m_user.synid
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public String getSynid() {
        return synid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.synid
     *
     * @param synid the value for m_user.synid
     *
     * @mbggenerated Wed Jul 22 09:49:45 CST 2015
     */
    public void setSynid(String synid) {
        this.synid = synid == null ? null : synid.trim();
    }

	@Override
	public Collection<? extends GrantedAuthority> getAuthorities() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String getPassword() {
		// TODO Auto-generated method stub
		return this.getPsw();
	}

	@Override
	public String getUsername() {
		// TODO Auto-generated method stub
		return this.getLoginname();
	}

	@Override
	public boolean isAccountNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public boolean isAccountNonLocked() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public boolean isCredentialsNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public boolean isEnabled() {
		// TODO Auto-generated method stub
		return true;
	}
}