package com.mk.hms.model;

import java.math.BigDecimal;

public class Province {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_province.ProID
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    private Long proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_province.Code
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_province.ProName
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    private String proName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_province.ProSort
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    private Integer proSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_province.ProRemark
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    private String proRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_province.latitude
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_province.longitude
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    private BigDecimal longitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_province.ProID
     *
     * @return the value of t_province.ProID
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    public Long getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_province.ProID
     *
     * @param proId the value for t_province.ProID
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    public void setProId(Long proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_province.Code
     *
     * @return the value of t_province.Code
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_province.Code
     *
     * @param code the value for t_province.Code
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_province.ProName
     *
     * @return the value of t_province.ProName
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_province.ProName
     *
     * @param proName the value for t_province.ProName
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_province.ProSort
     *
     * @return the value of t_province.ProSort
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    public Integer getProSort() {
        return proSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_province.ProSort
     *
     * @param proSort the value for t_province.ProSort
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    public void setProSort(Integer proSort) {
        this.proSort = proSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_province.ProRemark
     *
     * @return the value of t_province.ProRemark
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    public String getProRemark() {
        return proRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_province.ProRemark
     *
     * @param proRemark the value for t_province.ProRemark
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    public void setProRemark(String proRemark) {
        this.proRemark = proRemark == null ? null : proRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_province.latitude
     *
     * @return the value of t_province.latitude
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_province.latitude
     *
     * @param latitude the value for t_province.latitude
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_province.longitude
     *
     * @return the value of t_province.longitude
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_province.longitude
     *
     * @param longitude the value for t_province.longitude
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }
}