package com.mk.hms.model;

import java.math.BigDecimal;
import java.util.Date;

public class TPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_price.id
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_price.roomTypeId
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    private Long roomTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_price.timeId
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    private Long timeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_price.price
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_price.subprice
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    private BigDecimal subprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_price.subper
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    private BigDecimal subper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_price.orderindex
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    private Integer orderIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_price.updateTime
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_price.id
     *
     * @return the value of t_price.id
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_price.id
     *
     * @param id the value for t_price.id
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_price.roomTypeId
     *
     * @return the value of t_price.roomTypeId
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    public Long getRoomTypeId() {
        return roomTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_price.roomTypeId
     *
     * @param roomTypeId the value for t_price.roomTypeId
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    public void setRoomTypeId(Long roomTypeId) {
        this.roomTypeId = roomTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_price.timeId
     *
     * @return the value of t_price.timeId
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    public Long getTimeId() {
        return timeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_price.timeId
     *
     * @param timeId the value for t_price.timeId
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    public void setTimeId(Long timeId) {
        this.timeId = timeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_price.price
     *
     * @return the value of t_price.price
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_price.price
     *
     * @param price the value for t_price.price
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_price.subprice
     *
     * @return the value of t_price.subprice
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    public BigDecimal getSubprice() {
        return subprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_price.subprice
     *
     * @param subprice the value for t_price.subprice
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    public void setSubprice(BigDecimal subprice) {
        this.subprice = subprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_price.subper
     *
     * @return the value of t_price.subper
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    public BigDecimal getSubper() {
        return subper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_price.subper
     *
     * @param subper the value for t_price.subper
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    public void setSubper(BigDecimal subper) {
        this.subper = subper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_price.orderindex
     *
     * @return the value of t_price.orderindex
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    public Integer getOrderIndex() {
        return orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_price.orderindex
     *
     * @param orderIndex the value for t_price.orderindex
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    public void setOrderIndex(Integer orderIndex) {
        this.orderIndex = orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_price.updateTime
     *
     * @return the value of t_price.updateTime
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_price.updateTime
     *
     * @param updateTime the value for t_price.updateTime
     *
     * @mbggenerated Fri Jul 24 18:13:25 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}