package com.mk.hms.mapper;

import com.mk.hms.model.BillCheckInfo;
import com.mk.hms.model.BillCheckInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BillCheckInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_check_info
     *
     * @mbggenerated Wed Jul 22 13:37:48 CST 2015
     */
    int countByExample(BillCheckInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_check_info
     *
     * @mbggenerated Wed Jul 22 13:37:48 CST 2015
     */
    int deleteByExample(BillCheckInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_check_info
     *
     * @mbggenerated Wed Jul 22 13:37:48 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_check_info
     *
     * @mbggenerated Wed Jul 22 13:37:48 CST 2015
     */
    int insert(BillCheckInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_check_info
     *
     * @mbggenerated Wed Jul 22 13:37:48 CST 2015
     */
    int insertSelective(BillCheckInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_check_info
     *
     * @mbggenerated Wed Jul 22 13:37:48 CST 2015
     */
    List<BillCheckInfo> selectByExample(BillCheckInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_check_info
     *
     * @mbggenerated Wed Jul 22 13:37:48 CST 2015
     */
    BillCheckInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_check_info
     *
     * @mbggenerated Wed Jul 22 13:37:48 CST 2015
     */
    int updateByExampleSelective(@Param("record") BillCheckInfo record, @Param("example") BillCheckInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_check_info
     *
     * @mbggenerated Wed Jul 22 13:37:48 CST 2015
     */
    int updateByExample(@Param("record") BillCheckInfo record, @Param("example") BillCheckInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_check_info
     *
     * @mbggenerated Wed Jul 22 13:37:48 CST 2015
     */
    int updateByPrimaryKeySelective(BillCheckInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_check_info
     *
     * @mbggenerated Wed Jul 22 13:37:48 CST 2015
     */
    int updateByPrimaryKey(BillCheckInfo record);
}