package com.mk.hms.mapper;

import com.mk.hms.model.BillConfirmCheck;
import com.mk.hms.model.BillConfirmCheckCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BillConfirmCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int countByExample(BillConfirmCheckCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int deleteByExample(BillConfirmCheckCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int insert(BillConfirmCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int insertSelective(BillConfirmCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    List<BillConfirmCheck> selectByExample(BillConfirmCheckCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    BillConfirmCheck selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int updateByExampleSelective(@Param("record") BillConfirmCheck record, @Param("example") BillConfirmCheckCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int updateByExample(@Param("record") BillConfirmCheck record, @Param("example") BillConfirmCheckCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int updateByPrimaryKeySelective(BillConfirmCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int updateByPrimaryKey(BillConfirmCheck record);
}