package com.mk.hms.mapper;

import com.mk.hms.model.BillOrders;
import com.mk.hms.model.BillOrdersCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BillOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_orders
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    int countByExample(BillOrdersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_orders
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    int deleteByExample(BillOrdersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_orders
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_orders
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    int insert(BillOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_orders
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    int insertSelective(BillOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_orders
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    List<BillOrders> selectByExample(BillOrdersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_orders
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    BillOrders selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_orders
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    int updateByExampleSelective(@Param("record") BillOrders record, @Param("example") BillOrdersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_orders
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    int updateByExample(@Param("record") BillOrders record, @Param("example") BillOrdersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_orders
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    int updateByPrimaryKeySelective(BillOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_orders
     *
     * @mbggenerated Sun Aug 02 10:58:17 CST 2015
     */
    int updateByPrimaryKey(BillOrders record);
}