package com.mk.hms.mapper;

import com.mk.hms.model.EBasePrice;
import com.mk.hms.model.EBasePriceCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EBasePriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_baseprice
     *
     * @mbggenerated Wed Jul 29 09:29:31 CST 2015
     */
    int countByExample(EBasePriceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_baseprice
     *
     * @mbggenerated Wed Jul 29 09:29:31 CST 2015
     */
    int deleteByExample(EBasePriceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_baseprice
     *
     * @mbggenerated Wed Jul 29 09:29:31 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_baseprice
     *
     * @mbggenerated Wed Jul 29 09:29:31 CST 2015
     */
    int insert(EBasePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_baseprice
     *
     * @mbggenerated Wed Jul 29 09:29:31 CST 2015
     */
    int insertSelective(EBasePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_baseprice
     *
     * @mbggenerated Wed Jul 29 09:29:31 CST 2015
     */
    List<EBasePrice> selectByExample(EBasePriceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_baseprice
     *
     * @mbggenerated Wed Jul 29 09:29:31 CST 2015
     */
    EBasePrice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_baseprice
     *
     * @mbggenerated Wed Jul 29 09:29:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") EBasePrice record, @Param("example") EBasePriceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_baseprice
     *
     * @mbggenerated Wed Jul 29 09:29:31 CST 2015
     */
    int updateByExample(@Param("record") EBasePrice record, @Param("example") EBasePriceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_baseprice
     *
     * @mbggenerated Wed Jul 29 09:29:31 CST 2015
     */
    int updateByPrimaryKeySelective(EBasePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_baseprice
     *
     * @mbggenerated Wed Jul 29 09:29:31 CST 2015
     */
    int updateByPrimaryKey(EBasePrice record);
}