package com.mk.hms.mapper;

import com.mk.hms.model.EHotel;
import com.mk.hms.model.EHotelCriteria;
import com.mk.hms.model.EHotelWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EHotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hotel
     *
     * @mbggenerated Thu Aug 27 16:01:18 CST 2015
     */
    int countByExample(EHotelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hotel
     *
     * @mbggenerated Thu Aug 27 16:01:18 CST 2015
     */
    int deleteByExample(EHotelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hotel
     *
     * @mbggenerated Thu Aug 27 16:01:18 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hotel
     *
     * @mbggenerated Thu Aug 27 16:01:18 CST 2015
     */
    int insert(EHotelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hotel
     *
     * @mbggenerated Thu Aug 27 16:01:18 CST 2015
     */
    int insertSelective(EHotelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hotel
     *
     * @mbggenerated Thu Aug 27 16:01:18 CST 2015
     */
    List<EHotelWithBLOBs> selectByExampleWithBLOBs(EHotelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hotel
     *
     * @mbggenerated Thu Aug 27 16:01:18 CST 2015
     */
    List<EHotel> selectByExample(EHotelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hotel
     *
     * @mbggenerated Thu Aug 27 16:01:18 CST 2015
     */
    EHotelWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hotel
     *
     * @mbggenerated Thu Aug 27 16:01:18 CST 2015
     */
    int updateByExampleSelective(@Param("record") EHotelWithBLOBs record, @Param("example") EHotelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hotel
     *
     * @mbggenerated Thu Aug 27 16:01:18 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") EHotelWithBLOBs record, @Param("example") EHotelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hotel
     *
     * @mbggenerated Thu Aug 27 16:01:18 CST 2015
     */
    int updateByExample(@Param("record") EHotel record, @Param("example") EHotelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hotel
     *
     * @mbggenerated Thu Aug 27 16:01:18 CST 2015
     */
    int updateByPrimaryKeySelective(EHotelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hotel
     *
     * @mbggenerated Thu Aug 27 16:01:18 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(EHotelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hotel
     *
     * @mbggenerated Thu Aug 27 16:01:18 CST 2015
     */
    int updateByPrimaryKey(EHotel record);
}