package com.mk.hms.mapper;

import com.mk.hms.model.ERoomtypeFacility;
import com.mk.hms.model.ERoomtypeFacilityCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ERoomtypeFacilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_roomtype_facility
     *
     * @mbggenerated Sun Aug 02 13:17:15 CST 2015
     */
    int countByExample(ERoomtypeFacilityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_roomtype_facility
     *
     * @mbggenerated Sun Aug 02 13:17:15 CST 2015
     */
    int deleteByExample(ERoomtypeFacilityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_roomtype_facility
     *
     * @mbggenerated Sun Aug 02 13:17:15 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_roomtype_facility
     *
     * @mbggenerated Sun Aug 02 13:17:15 CST 2015
     */
    int insert(ERoomtypeFacility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_roomtype_facility
     *
     * @mbggenerated Sun Aug 02 13:17:15 CST 2015
     */
    int insertSelective(ERoomtypeFacility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_roomtype_facility
     *
     * @mbggenerated Sun Aug 02 13:17:15 CST 2015
     */
    List<ERoomtypeFacility> selectByExample(ERoomtypeFacilityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_roomtype_facility
     *
     * @mbggenerated Sun Aug 02 13:17:15 CST 2015
     */
    ERoomtypeFacility selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_roomtype_facility
     *
     * @mbggenerated Sun Aug 02 13:17:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") ERoomtypeFacility record, @Param("example") ERoomtypeFacilityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_roomtype_facility
     *
     * @mbggenerated Sun Aug 02 13:17:15 CST 2015
     */
    int updateByExample(@Param("record") ERoomtypeFacility record, @Param("example") ERoomtypeFacilityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_roomtype_facility
     *
     * @mbggenerated Sun Aug 02 13:17:15 CST 2015
     */
    int updateByPrimaryKeySelective(ERoomtypeFacility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_roomtype_facility
     *
     * @mbggenerated Sun Aug 02 13:17:15 CST 2015
     */
    int updateByPrimaryKey(ERoomtypeFacility record);
}