package com.mk.hms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mk.hms.model.BillConfirmCheck;
import com.mk.hms.model.BillConfirmCheckCriteria;
import com.mk.hms.model.ExtBillConfirmCheck;
import com.mk.hms.model.ExtBillConfirmCheckCriteria;

public interface ExtBillConfirmCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    List<Long> countByExample(ExtBillConfirmCheckCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int deleteByExample(ExtBillConfirmCheckCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int insert(ExtBillConfirmCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int insertSelective(ExtBillConfirmCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    List<ExtBillConfirmCheck> selectByExample(ExtBillConfirmCheckCriteria example);

//    @Select("select * from b_bill_confirm_check where ${where} order by billtime desc limit #{pageNum}, #{pageSize}")
//	List<HmsBBillConfirmCheckModel> findBillByWhere(@Param("where") String where, @Param("pageNum") int pageNum,
//			@Param("pageSize") int pageSize);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    ExtBillConfirmCheck selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int updateByExampleSelective(@Param("record") ExtBillConfirmCheck record, @Param("example") ExtBillConfirmCheckCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int updateByExample(@Param("record") ExtBillConfirmCheck record, @Param("example") ExtBillConfirmCheckCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int updateByPrimaryKeySelective(ExtBillConfirmCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bill_confirm_check
     *
     * @mbggenerated Wed Jul 22 11:05:41 CST 2015
     */
    int updateByPrimaryKey(ExtBillConfirmCheck record);
    
    int updateCheckStatus(@Param("id") long id);
}