package com.mk.hms.mapper;

import com.mk.hms.model.HotelOperateLog;
import com.mk.hms.model.HotelOperateLogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotelOperateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_operate_log
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    int countByExample(HotelOperateLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_operate_log
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    int deleteByExample(HotelOperateLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_operate_log
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_operate_log
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    int insert(HotelOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_operate_log
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    int insertSelective(HotelOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_operate_log
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    List<HotelOperateLog> selectByExample(HotelOperateLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_operate_log
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    HotelOperateLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_operate_log
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") HotelOperateLog record, @Param("example") HotelOperateLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_operate_log
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    int updateByExample(@Param("record") HotelOperateLog record, @Param("example") HotelOperateLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_operate_log
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    int updateByPrimaryKeySelective(HotelOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_operate_log
     *
     * @mbggenerated Fri Jul 24 17:56:26 CST 2015
     */
    int updateByPrimaryKey(HotelOperateLog record);
}