package com.mk.hms.mapper;

import com.mk.hms.model.HotelBillSplit;
import com.mk.hms.model.HotelBillSplitCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotelBillSplitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_hotel_bill_split
     *
     * @mbggenerated Wed Jul 22 16:24:23 CST 2015
     */
    int countByExample(HotelBillSplitCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_hotel_bill_split
     *
     * @mbggenerated Wed Jul 22 16:24:23 CST 2015
     */
    int deleteByExample(HotelBillSplitCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_hotel_bill_split
     *
     * @mbggenerated Wed Jul 22 16:24:23 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_hotel_bill_split
     *
     * @mbggenerated Wed Jul 22 16:24:23 CST 2015
     */
    int insert(HotelBillSplit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_hotel_bill_split
     *
     * @mbggenerated Wed Jul 22 16:24:23 CST 2015
     */
    int insertSelective(HotelBillSplit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_hotel_bill_split
     *
     * @mbggenerated Wed Jul 22 16:24:23 CST 2015
     */
    List<HotelBillSplit> selectByExample(HotelBillSplitCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_hotel_bill_split
     *
     * @mbggenerated Wed Jul 22 16:24:23 CST 2015
     */
    HotelBillSplit selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_hotel_bill_split
     *
     * @mbggenerated Wed Jul 22 16:24:23 CST 2015
     */
    int updateByExampleSelective(@Param("record") HotelBillSplit record, @Param("example") HotelBillSplitCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_hotel_bill_split
     *
     * @mbggenerated Wed Jul 22 16:24:23 CST 2015
     */
    int updateByExample(@Param("record") HotelBillSplit record, @Param("example") HotelBillSplitCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_hotel_bill_split
     *
     * @mbggenerated Wed Jul 22 16:24:23 CST 2015
     */
    int updateByPrimaryKeySelective(HotelBillSplit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_hotel_bill_split
     *
     * @mbggenerated Wed Jul 22 16:24:23 CST 2015
     */
    int updateByPrimaryKey(HotelBillSplit record);
}