package com.mk.hms.mapper;

import com.mk.hms.model.InstantMessage;
import com.mk.hms.model.InstantMessageCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InstantMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_instant_message
     *
     * @mbggenerated Tue Jul 28 18:43:50 CST 2015
     */
    int countByExample(InstantMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_instant_message
     *
     * @mbggenerated Tue Jul 28 18:43:50 CST 2015
     */
    int deleteByExample(InstantMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_instant_message
     *
     * @mbggenerated Tue Jul 28 18:43:50 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_instant_message
     *
     * @mbggenerated Tue Jul 28 18:43:50 CST 2015
     */
    int insert(InstantMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_instant_message
     *
     * @mbggenerated Tue Jul 28 18:43:50 CST 2015
     */
    int insertSelective(InstantMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_instant_message
     *
     * @mbggenerated Tue Jul 28 18:43:50 CST 2015
     */
    List<InstantMessage> selectByExample(InstantMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_instant_message
     *
     * @mbggenerated Tue Jul 28 18:43:50 CST 2015
     */
    InstantMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_instant_message
     *
     * @mbggenerated Tue Jul 28 18:43:50 CST 2015
     */
    int updateByExampleSelective(@Param("record") InstantMessage record, @Param("example") InstantMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_instant_message
     *
     * @mbggenerated Tue Jul 28 18:43:50 CST 2015
     */
    int updateByExample(@Param("record") InstantMessage record, @Param("example") InstantMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_instant_message
     *
     * @mbggenerated Tue Jul 28 18:43:50 CST 2015
     */
    int updateByPrimaryKeySelective(InstantMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_instant_message
     *
     * @mbggenerated Tue Jul 28 18:43:50 CST 2015
     */
    int updateByPrimaryKey(InstantMessage record);
}