package com.mk.hms.mapper;

import com.mk.hms.model.OrderDetail;
import com.mk.hms.model.OrderDetailCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_shopping_order_detail
     *
     * @mbggenerated Thu Jul 30 12:09:14 CST 2015
     */
    int countByExample(OrderDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_shopping_order_detail
     *
     * @mbggenerated Thu Jul 30 12:09:14 CST 2015
     */
    int deleteByExample(OrderDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_shopping_order_detail
     *
     * @mbggenerated Thu Jul 30 12:09:14 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_shopping_order_detail
     *
     * @mbggenerated Thu Jul 30 12:09:14 CST 2015
     */
    int insert(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_shopping_order_detail
     *
     * @mbggenerated Thu Jul 30 12:09:14 CST 2015
     */
    int insertSelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_shopping_order_detail
     *
     * @mbggenerated Thu Jul 30 12:09:14 CST 2015
     */
    List<OrderDetail> selectByExample(OrderDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_shopping_order_detail
     *
     * @mbggenerated Thu Jul 30 12:09:14 CST 2015
     */
    OrderDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_shopping_order_detail
     *
     * @mbggenerated Thu Jul 30 12:09:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") OrderDetail record, @Param("example") OrderDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_shopping_order_detail
     *
     * @mbggenerated Thu Jul 30 12:09:14 CST 2015
     */
    int updateByExample(@Param("record") OrderDetail record, @Param("example") OrderDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_shopping_order_detail
     *
     * @mbggenerated Thu Jul 30 12:09:14 CST 2015
     */
    int updateByPrimaryKeySelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_shopping_order_detail
     *
     * @mbggenerated Thu Jul 30 12:09:14 CST 2015
     */
    int updateByPrimaryKey(OrderDetail record);
}