package com.mk.hms.mapper;

import com.mk.hms.model.OtaOrder;
import com.mk.hms.model.OtaOrderCriteria;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OtaOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_otaorder
     *
     * @mbggenerated Thu Jul 30 12:15:03 CST 2015
     */
    int countByExample(OtaOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_otaorder
     *
     * @mbggenerated Thu Jul 30 12:15:03 CST 2015
     */
    int deleteByExample(OtaOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_otaorder
     *
     * @mbggenerated Thu Jul 30 12:15:03 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_otaorder
     *
     * @mbggenerated Thu Jul 30 12:15:03 CST 2015
     */
    int insert(OtaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_otaorder
     *
     * @mbggenerated Thu Jul 30 12:15:03 CST 2015
     */
    int insertSelective(OtaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_otaorder
     *
     * @mbggenerated Thu Jul 30 12:15:03 CST 2015
     */
    List<OtaOrder> selectByExampleWithBLOBs(OtaOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_otaorder
     *
     * @mbggenerated Thu Jul 30 12:15:03 CST 2015
     */
    List<OtaOrder> selectByExample(OtaOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_otaorder
     *
     * @mbggenerated Thu Jul 30 12:15:03 CST 2015
     */
    OtaOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_otaorder
     *
     * @mbggenerated Thu Jul 30 12:15:03 CST 2015
     */
    int updateByExampleSelective(@Param("record") OtaOrder record, @Param("example") OtaOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_otaorder
     *
     * @mbggenerated Thu Jul 30 12:15:03 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") OtaOrder record, @Param("example") OtaOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_otaorder
     *
     * @mbggenerated Thu Jul 30 12:15:03 CST 2015
     */
    int updateByExample(@Param("record") OtaOrder record, @Param("example") OtaOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_otaorder
     *
     * @mbggenerated Thu Jul 30 12:15:03 CST 2015
     */
    int updateByPrimaryKeySelective(OtaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_otaorder
     *
     * @mbggenerated Thu Jul 30 12:15:03 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(OtaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_otaorder
     *
     * @mbggenerated Thu Jul 30 12:15:03 CST 2015
     */
    int updateByPrimaryKey(OtaOrder record);

    public Date queryCheckoutTime(@Param(value ="id")Long id);
}