package com.mk.hms.mapper;

import com.mk.hms.model.Province;
import com.mk.hms.model.ProvinceCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    int countByExample(ProvinceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    int deleteByExample(ProvinceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    int deleteByPrimaryKey(Long proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    int insert(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    int insertSelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    List<Province> selectByExample(ProvinceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    Province selectByPrimaryKey(Long proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    int updateByExampleSelective(@Param("record") Province record, @Param("example") ProvinceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    int updateByExample(@Param("record") Province record, @Param("example") ProvinceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    int updateByPrimaryKeySelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbggenerated Thu Jul 23 10:35:47 CST 2015
     */
    int updateByPrimaryKey(Province record);
}