package com.mk.hms.mapper;

import com.mk.hms.model.Role;
import com.mk.hms.model.RoleCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_Role
     *
     * @mbggenerated Mon Jul 20 13:47:00 CST 2015
     */
    int countByExample(RoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_Role
     *
     * @mbggenerated Mon Jul 20 13:47:00 CST 2015
     */
    int deleteByExample(RoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_Role
     *
     * @mbggenerated Mon Jul 20 13:47:00 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_Role
     *
     * @mbggenerated Mon Jul 20 13:47:00 CST 2015
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_Role
     *
     * @mbggenerated Mon Jul 20 13:47:00 CST 2015
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_Role
     *
     * @mbggenerated Mon Jul 20 13:47:00 CST 2015
     */
    List<Role> selectByExample(RoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_Role
     *
     * @mbggenerated Mon Jul 20 13:47:00 CST 2015
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_Role
     *
     * @mbggenerated Mon Jul 20 13:47:00 CST 2015
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_Role
     *
     * @mbggenerated Mon Jul 20 13:47:00 CST 2015
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_Role
     *
     * @mbggenerated Mon Jul 20 13:47:00 CST 2015
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_Role
     *
     * @mbggenerated Mon Jul 20 13:47:00 CST 2015
     */
    int updateByPrimaryKey(Role record);
}