package com.mk.hms.mapper;

import com.mk.hms.model.RoomType;
import com.mk.hms.model.RoomTypeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoomTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_roomtype
     *
     * @mbggenerated Wed Jul 29 07:33:29 CST 2015
     */
    int countByExample(RoomTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_roomtype
     *
     * @mbggenerated Wed Jul 29 07:33:29 CST 2015
     */
    int deleteByExample(RoomTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_roomtype
     *
     * @mbggenerated Wed Jul 29 07:33:29 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_roomtype
     *
     * @mbggenerated Wed Jul 29 07:33:29 CST 2015
     */
    int insert(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_roomtype
     *
     * @mbggenerated Wed Jul 29 07:33:29 CST 2015
     */
    int insertSelective(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_roomtype
     *
     * @mbggenerated Wed Jul 29 07:33:29 CST 2015
     */
    List<RoomType> selectByExample(RoomTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_roomtype
     *
     * @mbggenerated Wed Jul 29 07:33:29 CST 2015
     */
    RoomType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_roomtype
     *
     * @mbggenerated Wed Jul 29 07:33:29 CST 2015
     */
    int updateByExampleSelective(@Param("record") RoomType record, @Param("example") RoomTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_roomtype
     *
     * @mbggenerated Wed Jul 29 07:33:29 CST 2015
     */
    int updateByExample(@Param("record") RoomType record, @Param("example") RoomTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_roomtype
     *
     * @mbggenerated Wed Jul 29 07:33:29 CST 2015
     */
    int updateByPrimaryKeySelective(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_roomtype
     *
     * @mbggenerated Wed Jul 29 07:33:29 CST 2015
     */
    int updateByPrimaryKey(RoomType record);

    Long getSaleConfigByRoomTypeId(@Param("roomTypeId") Long roomTypeId);
}