package com.mk.hms.mapper;

import com.mk.hms.model.THotel;
import com.mk.hms.model.THotelCriteria;
import com.mk.hms.model.THotelWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface THotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Thu Aug 27 16:10:38 CST 2015
     */
    int countByExample(THotelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Thu Aug 27 16:10:38 CST 2015
     */
    int deleteByExample(THotelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Thu Aug 27 16:10:38 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Thu Aug 27 16:10:38 CST 2015
     */
    int insert(THotelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Thu Aug 27 16:10:38 CST 2015
     */
    int insertSelective(THotelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Thu Aug 27 16:10:38 CST 2015
     */
    List<THotelWithBLOBs> selectByExampleWithBLOBs(THotelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Thu Aug 27 16:10:38 CST 2015
     */
    List<THotel> selectByExample(THotelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Thu Aug 27 16:10:38 CST 2015
     */
    THotelWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Thu Aug 27 16:10:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") THotelWithBLOBs record, @Param("example") THotelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Thu Aug 27 16:10:38 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") THotelWithBLOBs record, @Param("example") THotelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Thu Aug 27 16:10:38 CST 2015
     */
    int updateByExample(@Param("record") THotel record, @Param("example") THotelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Thu Aug 27 16:10:38 CST 2015
     */
    int updateByPrimaryKeySelective(THotelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Thu Aug 27 16:10:38 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(THotelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel
     *
     * @mbggenerated Thu Aug 27 16:10:38 CST 2015
     */
    int updateByPrimaryKey(THotel record);
}