package com.mk.hms.mapper;

import com.mk.hms.model.UserRole;
import com.mk.hms.model.UserRoleCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user_role
     *
     * @mbggenerated Mon Jul 20 17:56:08 CST 2015
     */
    int countByExample(UserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user_role
     *
     * @mbggenerated Mon Jul 20 17:56:08 CST 2015
     */
    int deleteByExample(UserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user_role
     *
     * @mbggenerated Mon Jul 20 17:56:08 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user_role
     *
     * @mbggenerated Mon Jul 20 17:56:08 CST 2015
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user_role
     *
     * @mbggenerated Mon Jul 20 17:56:08 CST 2015
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user_role
     *
     * @mbggenerated Mon Jul 20 17:56:08 CST 2015
     */
    List<UserRole> selectByExample(UserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user_role
     *
     * @mbggenerated Mon Jul 20 17:56:08 CST 2015
     */
    UserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user_role
     *
     * @mbggenerated Mon Jul 20 17:56:08 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserRole record, @Param("example") UserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user_role
     *
     * @mbggenerated Mon Jul 20 17:56:08 CST 2015
     */
    int updateByExample(@Param("record") UserRole record, @Param("example") UserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user_role
     *
     * @mbggenerated Mon Jul 20 17:56:08 CST 2015
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user_role
     *
     * @mbggenerated Mon Jul 20 17:56:08 CST 2015
     */
    int updateByPrimaryKey(UserRole record);
}